export const profile = {
  name: "Shravan Paladugula",
  shortName: "Shravan",
  monogram: "SP",
  role: "Incoming Computer Engineering · UC San Diego",
  headline: "I build systems that leave the screen.",
  tagline:
    "Incoming B.S. Computer Engineering at UC San Diego — embedded systems, firmware, edge AI, and full-stack fabrication pipelines.",
  location: "Mountain House, CA → La Jolla, CA",
  email: "shravan.paladugula@gmail.com",
  phone: "(925) 493-9513",
  links: {
    github: "https://github.com/ShravanPaladugula",
    linkedin: "https://linkedin.com/in/shravan-paladugula",
    devpost: "https://devpost.com/ShravanPaladugula",
    resume: "/resume.pdf",
  },
  about: {
    title: "Engineering starts where code meets matter.",
    paragraphs: [
      "I am most interested in the point where software becomes a physical system — sensors, firmware, PCBs, enclosures, and the pipelines that turn an idea into something you can hold.",
      "My work spans edge AI attendance hardware, voice-to-fabrication agents, clinical communication devices, and SAR drone platforms. Outside the lab I lead MountainHacks and build nonprofit infrastructure at ServingHandz.",
    ],
  },
  signals: [
    { value: "13", label: "hackathon wins across 15 events" },
    { value: "2×", label: "CruzHacks Best Hardware Hack" },
    { value: "500+", label: "hackathon club members led" },
    { value: "$3K+", label: "Central Valley Printing revenue" },
  ],
  systems: {
    embedded: [
      "ESP32",
      "Arduino",
      "Raspberry Pi",
      "Orange Pi",
      "KiCAD",
      "Fusion 360",
      "3D printing",
      "UART / I2C / SPI",
      "PWM / PID",
      "LiPo power",
    ],
    firmware: [
      "C / C++",
      "Python",
      "MATLAB",
      "Embedded Linux",
      "OTA pipelines",
      "OpenSCAD",
      "CuraEngine",
      "Moonraker",
      "Sensor fusion",
    ],
    fullstack: [
      "TypeScript",
      "React",
      "FastAPI",
      "Node.js",
      "Supabase",
      "Three.js",
      "OpenCV",
      "Vercel",
      "GitHub Actions",
    ],
  },
  education: [
    {
      school: "University of California, San Diego",
      detail: "B.S. Computer Engineering · Jacobs School of Engineering",
      when: "Incoming Fall 2026 · Sep 2026 – May 2030",
      place: "La Jolla, CA",
    },
    {
      school: "Mountain House High School",
      detail: "GPA 4.64 · Ranked 6/615 · Distinguished Award (Top 2%) · AP Scholar with Distinction",
      when: "May 2026",
      place: "Mountain House, CA",
    },
  ],
} as const;
